# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Walter Zimmer"
resume_title:                   "Machine Learning Researcher"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "walterzimmer@gmx.de"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(+49) 015 678 365 392"
resume_contact_address:         "Freisinger Landstrasse 17, 80939 Freimann, Germany"

resume_header_contact_info:     "Freisinger Landstrasse 17, 80939 Freimann • (+49) 015 678 365 392 • walterzimmer@gmx.de"
display_header_contact_info:    "false"

resume_header_intro: "<p>I work as an Autonomous Driving Research Engineer, and my passion lies in making autonomous vehicles safer. I've dived deep into the world of Machine Learning, during my academic journey at the Cooperative State University, the Technical University of Munich, Delft University of Technology and the University of California in San Diego. Using my programming skills I love to solve hard research problems and develop new approaches. My strength lies in understanding the scene around self-driving cars, especially in 3D Object Detection. I have got hands-on experience dealing with sensor data at the the sensor data fusion department of Audi, where I have contributed to generate accurate ground truth datasets. Additionally, I got accepted for a visiting scholar position abroad at the Laboratory of Intelligent and Safe Automobiles (LISA) in San Diego (UCSD). Here, I have developed a 3D annotation toolbox to label LiDAR and camera data of a Tesla Model S, showcasing my commitment to pushing boundaries of this technology.</br></br>

Technical skills:
<ul class='resume-item-list'>
    <li>Autonomous Driving, Deep Learning, Computer Vision</li>
    <li>Python, PyTorch3D, Open3D </li>
    <li>C++, TensorFlow 3D</li>
    <li>Test Driven Development (TDD), PyTest, Google Test</li>
    <li>Continuous Integration, Docker, Kubernetes</li>
    <li>ROS, Sensor Fusion (camera, LiDAR)</li>
    <li>SCRUM, Agile Development</li>
    <li>Algorithm Design, Research, Technical Writing</li>
</ul>

Soft skills:
<ul class='resume-item-list'>
<li>Problem Solving</li>
    <li>Teamwork, Team Leadership</li>
    <li>Decision Making</li>
    <li>Project Management, Time Management</li>
    <li>Public Speaking, Teaching, Networking</li>
    <li>Attention to Detail</li>
</ul>
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_hard_skills:          true
resume_section_soft_skills:          true
resume_section_publications:     true
resume_section_awards:     true
resume_section_certificates:     true
resume_section_links:           false
resume_section_memberships:    true
resume_section_references:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/walzimmer"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/walterzimmer"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
