# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Walter Zimmer"
resume_title:                   "Machine Learning Researcher"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "walterzimmer@gmx.de"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(+49) 173 8167062"
resume_contact_address:         "Jägerstraße 29A, 82008 Unterhaching"

resume_header_contact_info:     "Jägerstraße 29A, 82008 Unterhaching • (+49) 173 8167062 • walterzimmer@gmx.de"
display_header_contact_info:    "false"

resume_header_intro: "<p>I'm an Autonomous Driving Research Engineer and I'm particularly interested in improving safety of autonomous vehicles. I have focused on Machine Learning at the Technical University of Munich, Delft University of Technology and the University of California in San Diego, where I developed Machine Learning algorithms for a Tesla Model S. Using my programming skills I love to solve hard research problems and develop new approaches. My strength is in understanding the scene around a self-driving car (perception) and particularly 3D Object Detection. I have worked with sensor data at Audi at the sensor data fusion department and was researcher at the Laboratory of Intelligent and Safe Automobiles (LISA) in San Diego.</br></br>

I have expert knowledge in:
<ul class='resume-item-list'>
  <li>Machine Learning, Deep Learning, Robotics</li>
  <li>Python, TensorFlow, Keras, Convolutional Neural Networks (CNNs)</li>
  <li>C++, Java, Object Oriented Design, Design Pattern</li>
  <li>Test Driven Development (TDD), Continuous Integration</li>
  <li>GPU programming</li>
  <li>Docker</li>
  <li>Algorithm Design</li>
 </ul>

Experience in:
<ul class='resume-item-list'>
  <li>working with sensor data (camera, LiDAR, radar, IMU, GPS)</li>
  <li>Sensor Fusion (camera, LiDAR)</li>
  <li>ROS</li>
  <li>Kubernetes</li>
  <li>AWS, Google Cloud</li>
  <li>Spark</li>
  <li>SCRUM, agile processes</li>
</ul>
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_hard_skills:          true
resume_section_soft_skills:          true
resume_section_publications:     true
resume_section_awards:     true
resume_section_certificates:     true
resume_section_links:           false
resume_section_memberships:    true
resume_section_references:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/walzimmer"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/walterzimmer"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
